class_name Types

enum Faction { PLAYER, ENEMY }
enum BuildingKind { HABITAT, DEPOT, WALL, TURRET, WORKSHOP, FARM, LAB, MEDBAY, GATE, RADAR }
enum UnitKind { PLAYER, RAIDER, GUARD }
enum ResourceKind { SCRAP, ICE, ORE, PARTS, FOOD }
enum TechKind { HYDROPONICS, METALLURGY, FIELD_MEDICINE, BALLISTICS }
enum TileTerrain { EMPTY, ROCK, CLIFF, CRATER }
enum Outcome { NONE, PLAYER_WIN, PLAYER_LOSE }
enum OutcomeReason { NONE, SUFFOCATION }
enum RaiderState {
	SPAWNED,
	PATH_TO_DEPOT,
	LOOT,
	PATH_HOME,
	CHASE,
	PATH_TO_HABITAT,
	ATTACK_HABITAT,
	SIEGE,
	DEAD_DROP,
}
